# =========================
# MySQL (BD: northwind)
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/northwind?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# Server
# =========================
server.port=8080
spring.application.name=lab_1806

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Ejecuta schema.sql automáticamente al arrancar (crea la tabla si no existe)
spring.sql.init.mode=always

# =========================
# Thymeleaf (cache off en dev)
# =========================
spring.thymeleaf.cache=false

# =========================
# Logging
# =========================
logging.level.com.lab.lab1806=DEBUG
